import Head from 'next/head';
import Image from 'next/image';
import { useSelector } from 'react-redux';
import Decrement from '../components/Decrement';
import Increment from '../components/Increment';
import styles from '../styles/Home.module.css';

export default function Home() {
  const count = useSelector((state) => state.counter.value);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Increment />
      <Decrement />
      {count}
    </div>
  );
}
